### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by Revod** [carloscuesta/starterkit#54]
When I run 'gulp' I get this:
```
revod at Revods-iMac in /Volumes/Files/Development/Frontend-Boilerplate on master ✗               [752f793]  12:25
> gulp
[12:26:03] Requiring external module babel-register
[12:26:05] Using gulpfile /Volumes/Files/Development/Frontend-Boilerplate/gulpfile.babel.js
[12:26:05] Starting 'default'...
[12:26:05] Starting 'templates'...
[12:26:05] Starting 'styles'...
[12:26:05] Starting 'scripts'...
[12:26:05] Starting 'images'...
[12:26:05] Finished 'images' after 971 μs
[12:26:05] Starting 'serve'...
[12:26:05] Finished 'serve' after 40 ms
[12:26:05] Finished 'default' after 61 ms
[BS] Access URLs:
 ---------------------------------------
       Local: http://localhost:3000
    External: http://192.168.20.160:3000
 ---------------------------------------
          UI: http://localhost:3001
 UI External: http://192.168.20.160:3001
 ---------------------------------------
[BS] Serving files from: ./dist/

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: spawn /Volumes/Files/Development/Frontend-Boilerplate/node_modules/optipng-bin/vendor/optipng ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

![screen shot 2016-11-21 at 12 29 53](https://cloud.githubusercontent.com/assets/10109689/20490988/3bb870cc-afe6-11e6-8924-adb534ca6c35.png)
![screen shot 2016-11-21 at 12 30 36](https://cloud.githubusercontent.com/assets/10109689/20491013/5a7e3366-afe6-11e6-9e0c-41b42668c7ff.png)

**Comment by carloscuesta** [comment]
That's a little bit weird, will take a look @Revod

**Comment by Revod** [comment]
@carloscuesta Thank you, I'm using node 7.0, npm 3.10.8 & macOS Sierra 10.12.2 Beta 3 and I update all the packages to the latest version using ncu before install: https://github.com/tjunnone/npm-check-updates then run npm install

**Comment by carloscuesta** [comment]
No issues for me @ node 6.9.1, could you try to delete the node_modules folder and do a reinstall?

**Comment by Revod** [comment]
That fixed the problem, thank you
